version: '2'
plugins:
  similar-code:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  identical-code:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
exclude_patterns:
  - '**/dist/**'
  - '**/test/**'
  - '**/tests/**'
  - '**/*.test.js'
  - '**/jest.config.js'
  - '.yarn/**'
  - '**/__mocks__/**'
